title: Ajay Sharma
logo: /assets/img/ajay.png
description: Software Engineer with 8 years experience in ASP.NET, Ruby on Rails, Terraform, Python.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
